-- Add missing columns to requests table
ALTER TABLE requests 
ADD COLUMN IF NOT EXISTS request_title VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS date_time DATETIME DEFAULT NULL,
ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS wage_amount DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS wage_type VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS contact_info VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS message TEXT DEFAULT NULL;
